server:
  port: 8080


spring:
  application:
    name: client

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: d5f15604b14fdbaebde0
            client-secret: c9bd21b2d5c4f13e61f4e08b9246b064fcb1b248
            scope:
              - user:email
              - read:user

logging:
  level:
    org.springframework.security: TRACE